user:
  max_name_length: 50
  max_pass_length: 6
helper:
  size: 80
paging:
  p10: 10
mailer:
  from: "noreply@example.com"
expired:
  value: 2
micropost:
  mb: 5
  width: 500
  height: 500
  max_value: 140
show:
  value: 30
